<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<form method="POST">
   <input type="text" name="gutem" id="gutem">
   <input type="submit" value="Enviar">
   </form>
        
    
    
    <?php
    extract($_POST);
    $userLog = $gutem;
    echo $userLog;
    
    //outra maneira de se fazer
    /*

    $gutin = $_POST['gutem']; 

    */

    ?>



</body>
</html>